/**
 * Significados en español para los kanji que KANJIDIC2 no cubre.
 *
 * Son casi todos jōyō incorporados en la revisión de 2010, posterior al
 * trabajo de traducción al español del propio KANJIDIC2. Traducidos desde
 * los significados en inglés de la misma entrada.
 */
export const ES_FALLBACK: Record<string, string[]> = {
  侶: ['compañero', 'camarada'],
  傲: ['orgullo', 'arrogancia'],
  凄: ['escalofriante', 'siniestro', 'tremendo'],
  刹: ['templo', 'instante'],
  剝: ['pelar', 'despegar', 'desprenderse'],
  剥: ['pelar', 'despegar', 'desprenderse'],
  勾: ['curvar', 'pendiente', 'detener'],
  唾: ['saliva', 'escupir'],
  嗅: ['oler', 'olfatear'],
  嘲: ['burlarse', 'mofarse'],
  塞: ['obstruir', 'tapar', 'fortaleza'],
  塡: ['rellenar', 'colmar'],
  填: ['rellenar', 'colmar'],
  妬: ['celos', 'envidia'],
  嫉: ['celos', 'envidiar'],
  弄: ['juguetear', 'manosear', 'burlarse'],
  彙: ['categoría', 'recopilación'],
  怨: ['rencor', 'resentimiento'],
  恣: ['arbitrario', 'egoísta'],
  惧: ['temor', 'recelo'],
  慄: ['estremecerse', 'pavor'],
  憬: ['anhelar', 'admirar'],
  拉: ['secuestrar', 'arrastrar'],
  捗: ['progresar', 'avanzar'],
  捻: ['retorcer', 'torcer'],
  摯: ['sinceridad', 'seriedad'],
  昧: ['oscuridad', 'ignorancia'],
  曖: ['ambiguo', 'turbio'],
  柵: ['empalizada', 'valla'],
  柿: ['caqui'],
  桁: ['viga', 'dígito'],
  梗: ['tallo', 'obstruir'],
  毀: ['destruir', 'dañar', 'difamar'],
  汎: ['general', 'pan-'],
  沃: ['fértil', 'fecundo'],
  淫: ['lujuria', 'lascivia'],
  潰: ['aplastar', 'derrumbar'],
  煎: ['tostar', 'hervir'],
  璧: ['esfera', 'joya'],
  畏: ['temor reverencial', 'respeto'],
  痕: ['marca', 'cicatriz', 'huella'],
  痩: ['adelgazar', 'enflaquecer'],
  瘍: ['úlcera', 'tumor'],
  窟: ['cueva', 'gruta'],
  箋: ['papel', 'etiqueta', 'nota'],
  緻: ['fino', 'minucioso'],
  罵: ['insultar', 'injuriar'],
  羞: ['vergüenza', 'pudor'],
  羨: ['envidiar', 'codiciar'],
  肘: ['codo'],
  腫: ['hinchazón', 'tumor'],
  舷: ['borda', 'costado del barco'],
  苛: ['atormentar', 'severo'],
  萎: ['marchitarse', 'decaer'],
  葛: ['kudzu', 'arrurruz'],
  蓋: ['tapa', 'cubierta'],
  蔑: ['despreciar', 'menospreciar'],
  蔽: ['encubrir', 'tapar'],
  訃: ['esquela', 'aviso de defunción'],
  詮: ['indagar', 'sentido'],
  諦: ['resignarse', 'renunciar', 'verdad'],
  諧: ['armonía', 'humor'],
  貌: ['apariencia', 'rostro'],
  貪: ['codiciar', 'ávido'],
  賂: ['soborno'],
  踪: ['rastro', 'paradero'],
  辣: ['picante', 'severo'],
  遜: ['humilde', 'modesto'],
  酎: ['licor destilado'],
  醒: ['despertar', 'desengañarse'],
  錮: ['confinamiento', 'encarcelar'],
  頰: ['mejilla'],
  顎: ['mandíbula', 'quijada'],
  鬱: ['melancolía', 'depresión'],
  '𠮟': ['regañar', 'reprender'],
}
